# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e83c419abce4def1ec20e614856ed466f17733a6ae113c7069783a47426bbe8160521512ac4891539597eb3b752a996f24a2bdd2e4c94c9f7d77480137dbfa7

test:
  secret_key_base: 2cb46c1d187a9d095574b7eb59cbb8b989455d977d222ad0858f53b10bfa2a33aeb5e6cab2a6bbf76ee23dfacf071a21d214bc24c5e6a00be127c40cbae311e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
